---

#### Môn học: Toán ứng dụng & thống kê
#### Lớp: CQ2022/2
#### Họ tên: Phạm Nguyễn Khánh Minh
#### MSSV: 20120117

---



<div style="text-align:center"><h1>LAB 1: Gauss Elimination and Back Substitution
</h1></div>

# Phép khử Gauss

**Khử Gauss** (Gaussian elimination) là một cách biến đổi tương đương dòng đưa ma trận về dạng bậc thang(tam giác trên). Thuật giải gồm các bước:

> **Bước 1**. Xác định cột trái nhất không chứa toàn số 0.

> **Bước 2**. Đổi chỗ hai dòng, nếu cần thiết, để đưa số hạng khác 0 nào đó ở dưới về đầu cột nhận được ở Bước 1.
*(Chọn dòng đầu tiên có số hạng khác 0. Phức tạp hơn, chiến lược "partial pivoting" chọn dòng có số hạng có trị tuyệt đối lớn nhất.)*

=> ***Phép biển đổi sơ cấp trên dòng Loại 1***

> **Bước 3**. Với số hạng đầu cột nhận được từ Bước 2 là $a\neq 0$ , nhân dòng chứa nó với $\frac{1}{a}$
 để có **số dẫn đầu** `1` (leading 1).
*(Bước này tùy chọn.)*

=> ***Phép biển đổi sơ cấp trên dòng Loại 2***

> **Bước 4**. Cộng một bội số thích hợp của dòng đầu cho từng dòng dưới để biến các số hạng bên dưới số dẫn đầu thành 0.

=> ***Phép biển đổi sơ cấp trên dòng loại 3***

> **Bước 5**. Che dòng đầu đã làm xong. Lặp lại các bước cho đến khi được ma trận bậc thang.

In [22]:
def Gauss_elimination(A):
    num_rows = len(A)
    num_cols = len(A[0])

    if not all(len(row) == num_cols for row in A):
        raise ValueError("All rows must have the same length")
    
    pivot_row = 0
    pivot_cols = 0
    
    while pivot_row < num_rows and pivot_cols < num_cols:
        max_row = pivot_row
        max_val = abs(A[pivot_row][pivot_cols])
       
        # Tìm hàng có giá trị lớn nhất trong cột pivot_cols từ hàng pivot_row trở đi
        for i in range(pivot_row + 1, num_rows):
            if abs(A[i][pivot_cols]) > max_val:
                max_row = i
                max_val = abs(A[i][pivot_cols])
        
        # Hoán vị hai hàng nếu cần
        if max_row != pivot_row:
            A[pivot_row], A[max_row] = A[max_row], A[pivot_row]
        
        # Kiểm tra nếu phần tử pivot là 0, nếu có, chuyển sang cột tiếp theo
        if A[pivot_row][pivot_cols] == 0:
            pivot_cols += 1
            continue

        # Chuyển các phần tử dưới pivot về 0
        for i in range(pivot_row + 1, num_rows):
            factor = A[i][pivot_cols] / A[pivot_row][pivot_cols]
            for j in range(pivot_cols, num_cols):
                A[i][j] -= factor * A[pivot_row][j]
        
        # Chuyển sang hàng tiếp theo và cột tiếp theo
        pivot_row += 1
        pivot_cols += 1

    return A


In [23]:
# Hàm in ma trận một cách đẹp
def print_matrix(matrix):
    for row in matrix:
        print(" | ".join(f"{val:8.2f}" if isinstance(val, float) else f"{val:8}" for val in row))

# Ma trận mở rộng đã nhập
A = [[2, 1, -1, 8],
     [-3, -1, 2, -11],
     [-2, 1, 2, -3]]

print("Ma trận mở rông đã nhập: ")
for row in A:
    print(row)

# Dạng ma trận bậc thang của ma trận mở rộng đã nhập
matrix =Gauss_elimination(A)

print("\nDạng ma trận bậc thang của ma trận mở rộng đã nhập: ")
for row in matrix:
    print(row)


Ma trận mở rông đã nhập: 
[2, 1, -1, 8]
[-3, -1, 2, -11]
[-2, 1, 2, -3]

Dạng ma trận bậc thang của ma trận mở rộng đã nhập: 
[-3, -1, 2, -11]
[0.0, 1.6666666666666665, 0.6666666666666667, 4.333333333333333]
[0.0, 0.0, 0.19999999999999987, -0.19999999999999984]


# Back_substitution

**Back_substitution**  là một cách Thế ngược ma trận bậc thang để tìm nghiệm của hệ phương trình

> **Bước 1**.: Biện luận trên các dòng gồm toàn số 0 của ma trận các hệ số. Nếu có một dòng gồm toàn số 0 của 

A mà hệ số vế phải (tự do) tương ứng là một số khác 0 thì kết luận hệ vô nghiệm và giải thuật chấm dứt. Ngược lại, bỏ tất cả các dòng gồm toàn số 0 (của ma trận các hệ số cũng như của vectơ các hệ số vế phải (tự do)) và chuyển qua bước 2.

> **Bước 2**.: Phép thế ngược (back substitution). Xác định các ẩn cơ sở là các ẩn tương ứng với các số dẫn đầu. Các ẩn còn lại được gọi là ẩn tự do (free variable).

Xét hai khả năng:
Không có ẩn tự do. Hệ có nghiệm duy nhất nhận được bằng cách giải từ dưới lên trên (backward).
Có ít nhất một ẩn tự do. Hệ có vô số nghiệm và nghiệm tổng quát nhận được bằng cách giải từ dưới lên tìm biểu thức của các ẩn dẫn đầu theo các tham số của ẩn tự do (tùy ý).








     hàm back_substitution(A), trong đó
• Input:
A, là ma trận có dạng bậc thang thu được từ ma trận mở rộng của hệ phương
trình: Ax =b 

• Output: nghiệm của hệ phương trình (trường hợp nghiệm duy nhất/ vô số nghiệm)
hoặc thông báo hệ phương trình vô nghiệm

In [24]:
import string
import numpy as np
from sympy import symbols

def is_leading_row(A: np.array, row: int, col: int) -> bool:
    result = bool
    check_sum = np.array(A[row][:col]).sum()

    if check_sum == 0:
        result = True
    else:
        result = False

    return result

def is_zero_matrix(A: np.array) -> bool:
    row, col = A.shape
    result = True

    for i in range(row):
        for j in range(col):
            if A[i][i] != 0:
                result = False
                return result
            
    return result

def extract_matrix(A: np.array) -> np.array:
    return (A.T)[0:-1].copy().T

def back_substitution(A) ->np.array:
    # Lấy số hàng và cột của ma trận
    row, col = A.shape
    col -= 1

    # Tạo một danh sách kết quả nghiệm
    x = np.zeros(col)

    # Xét từng hàng của ma trận bậc thang từ hàng cuối lên đầu
    for i in range(row - 1, -1, -1):
        colum = i

        while (A[i][colum] == 0 and colum < col):
            colum += 1

        if (colum == col):
            colum -= 1
        
        factor = A[i][colum] 
        const = A[i][col] # Giá trị hằng số
        
        # Nếu hệ số bằng 0 và hằng số khác 0 thì hệ phương trình vô nghiệm
        if factor == 0 and const != 0:
            print("Hệ phương trình vô nghiệm")
            return np.array(0)
        elif factor == 0 and const == 0:
            continue

        alphabet = symbols(list(string.ascii_lowercase))
        y = []
        index = 0

        # Duyệt trên đường bậc thang để đánh dấu nghiệm
        for i in range(col):
            i_rows = row - 1

            for _ in range(row):
                if A[i_rows][i] != 0:
                    if is_leading_row(A, i_rows, i):
                        y.append(0)
                    else:
                        y.append(alphabet[index])
                        index += 1
        
                    break
                else:
                    i_rows -= 1

        x = np.array(y)
        
        # Loại trừ trường hợp ma trận 0
        if is_zero_matrix(A) == True:
            x = [alphabet[index] for index in range(col)]
            return x

    # back_substitution để tính nghiệm
    i = col - 1
    while i >= 0:
        i_rows = row - 1

        for _ in range(row):
            if A[i_rows][i] != 0:
                if is_leading_row(A, i_rows, i) == True:
                    s = x.dot(extract_matrix(A)[i_rows])
                    x[i] = (A[i_rows][col] - s) / A[i_rows][i]

                break
            else:
                i_rows -= 1
        
        i -= 1

    return np.array(x).T


In [25]:
A = np.array([
    [1, 3, -1, 2 ,2 , 0],
    [0, 3, 3, 0 , 3 , -9],
    [0, 0, 1, -5 , 3 , -3],
    [0, 0, 0 ,-1 ,-1 ,8],
    [0, 0, 0, 0, 0, 0]
])


print(f"Ma trận mở rông (A|b) đã nhâp: \n{A}")

x = back_substitution(A)

if x.any():
        print("Nghiệm của hệ phương trình: ")
        for i in range(x.shape[0]):
            print(f"x{i+1} = {x[i]}")

Ma trận mở rông (A|b) đã nhâp: 
[[ 1  3 -1  2  2  0]
 [ 0  3  3  0  3 -9]
 [ 0  0  1 -5  3 -3]
 [ 0  0  0 -1 -1  8]
 [ 0  0  0  0  0  0]]
Nghiệm của hệ phương trình: 
x1 = -29*a - 147
x2 = 7*a + 40
x3 = -8*a - 43
x4 = -a - 8
x5 = a


# Mô tả các hàm 

             Gauss_elimination

- **Input**:
    - matrix: Ma trận mở rộng của hệ phương trình
- **Output**: Ma trận có dạng bậc thang có được từ ma trận mở rộng đầu vào
- **Mục đích**: Dùng phép khử Gauss để biến đổi ma trận mở rộng ban đầu của hệ phương trình về dạng bậc thang
- **Hoạt động**:

<strong> Giải thuật: </strong>




1. **Khởi tạo biến**: Đầu tiên, khởi tạo hai biến `pivot_row` và `pivot_cols` để theo dõi vị trí hàng và cột của phần tử pivot đang xét.

2. **Lặp qua các hàng và cột**: Sử dụng vòng lặp `while`, thuật toán sẽ lặp qua từng hàng và cột trong ma trận.

3. **Tìm phần tử pivot**: Trong mỗi vòng lặp, thuật toán sẽ tìm phần tử pivot, tức là phần tử không bằng 0 đầu tiên trong cột hiện tại, bắt đầu từ hàng `pivot_row`.

4. **Hoán vị hàng**: Nếu phần tử pivot không nằm ở hàng `pivot_row`, thuật toán sẽ hoán vị hai hàng để đưa phần tử pivot lớn nhất về hàng `pivot_row`.

5. **Kiểm tra phần tử pivot**: Nếu phần tử pivot tại hàng `pivot_row` và cột `pivot_cols` bằng 0, thuật toán sẽ tăng `pivot_cols` lên 1 và tiếp tục với cột tiếp theo.

6. **Biến đổi ma trận**: Nếu phần tử pivot không bằng 0, thuật toán sẽ sử dụng phần tử pivot để biến đổi các phần tử dưới nó thành 0 thông qua phép loại trừ Gauss.

7. **Cập nhật pivot_row và pivot_cols**: Sau khi biến đổi xong, thuật toán sẽ tăng `pivot_row` và `pivot_cols` lên 1 để di chuyển đến hàng và cột tiếp theo.

8. **Trả về kết quả**: Khi đã duyệt qua tất cả các hàng và cột, thuật toán sẽ trả về ma trận đã biến đổi.





<ol>
<code>back_substitution(A) -&gt; np.array</code> để thực hiện phương pháp thế ngược để giải hệ phương trình tuyến tính.
        <ul>
            <li>Xác định số hàng và cột của ma trận.</li>
            <li>Khởi tạo một mảng <code>x</code> chứa các nghiệm, ban đầu là một mảng các số 0 có kích thước bằng với số cột của ma trận.</li>
            <li>Bắt đầu từ hàng cuối cùng và đi lên trên.</li>
            <li>Đối với mỗi hàng, tìm cột dẫn đầu đầu tiên không chứa số 0, nếu có.</li>
            <li>Nếu không tìm thấy cột dẫn đầu, di chuyển sang hàng tiếp theo.</li>
            <li>Nếu tìm thấy cột dẫn đầu, tính nghiệm tương ứng cho biến của cột đó.</li>
            <li>Sử dụng phương pháp thế ngược để cập nhật các giá trị của các biến còn lại dựa trên nghiệm của biến dẫn đầu.</li>
            <li>Nếu ma trận là ma trận 0, trả về một mảng chứa các biến tự do.</li>
            <li>Trả về một mảng numpy chứa nghiệm của hệ phương trình.</li>
        </ul>
    
</ol>

       Hàm is_leading_row(A: np.array, row: int, col: int) -> bool:

Mục đích: Hàm này được sử dụng để kiểm tra xem một hàng có phải là hàng dẫn đầu không.
Hoạt động:
Tính tổng các phần tử bên trái của cột dẫn đầu của hàng cần kiểm tra bằng cách sử dụng phương thức sum() của thư viện NumPy.
So sánh tổng với 0. Nếu bằng 0, hàm trả về True để chỉ ra rằng hàng này là hàng dẫn đầu. Ngược lại, trả về False.

       Hàm is_zero_matrix(A: np.array) -> bool:

Mục đích: Hàm này được sử dụng để kiểm tra xem ma trận có phải là ma trận 0 không.
Hoạt động:
Duyệt qua từng phần tử của ma trận.
Nếu tìm thấy một phần tử khác 0, hàm trả về False để chỉ ra rằng ma trận không phải là ma trận 0.
Nếu không tìm thấy phần tử khác 0 sau khi duyệt hết, hàm trả về True để chỉ ra rằng ma trận là ma trận 0.

       Hàm extract_matrix(A: np.array) -> np.array:

Mục đích: Hàm này được sử dụng để trích xuất ma trận các hệ số từ ma trận mở rộng.
Hoạt động:
Chuyển vị của ma trận mở rộng để thuận tiện cho việc loại bỏ cột vế phải.
Loại bỏ cột cuối cùng (cột vế phải).
Chuyển vị trở lại để có kết quả cuối cùng.

# Mở rộng: tìm hiểu các hàm/ phương thức tương ứng của các thư viện

## TÌm ma trận bậc thang thư viện Numpy

In [26]:
import numpy as np
from scipy.linalg import lu

# Định nghĩa hàm Gauss_elimination
def Gauss_elimination(A):
    # Phân tích ma trận thành L và U
    P, L, U = lu(A)
    
    return U

# Tạo ma trận mở rộng A
A = [[2, 1, -1, 8],
     [-3, -1, 2, -11],
     [-2, 1, 2, -3]]


# Gọi hàm Gauss_elimination và nhận ma trận bậc thang U
U = Gauss_elimination(A)

print("Ma trận bậc thang U:")
print(U)


Ma trận bậc thang U:
[[ -3.          -1.           2.         -11.        ]
 [  0.           1.66666667   0.66666667   4.33333333]
 [  0.           0.           0.2         -0.2       ]]


## Giải hệ phương trình tuyến tính sử dụng thư viện SciPy

1. Import thư viện NumPy: Đầu tiên, chúng ta cần import thư viện NumPy.

2. Sử dụng hàm np.linalg.solve(): Thư viện NumPy cung cấp hàm np.linalg.solve() để giải hệ phương trình tuyến tính. Chúng ta sẽ sử dụng hàm này để tìm các nghiệm của hệ phương trình.

3. Gọi hàm np.linalg.solve() và truyền ma trận A và vectơ b vào đó: Trong trường hợp này, ma trận A đã cho không chứa vectơ kết quả. Chúng ta chỉ cần truyền ma trận A vào hàm np.linalg.solve().

4. Xem kết quả: Hàm np.linalg.solve() sẽ trả về các nghiệm của hệ phương trình, và sau đó chúng ta có thể in kết quả ra màn hình.

In [27]:
import numpy as np
from scipy.linalg import lu_factor, lu_solve

# Ma trận hệ số
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

# Ma trận kết quả
b = np.array([8, -11, -3])

# Phân tích LU
lu, piv = lu_factor(A)

# Giải hệ phương trình
x = lu_solve((lu, piv), b)

print(x)

[ 2.  3. -1.]


## Giải hệ phương trình tuyến tính sử dụng thư viện Numpy:

In [28]:
import numpy as np

# Hệ số của ma trận A
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

# Hệ số của vế phải (tự do) b
b = np.array([8, -11, -3])

# Giải hệ phương trình tuyến tính Ax = b sử dụng NumPy
x = np.linalg.solve(A, b)

print("Nghiệm của hệ phương trình tuyến tính:")
print(x)


Nghiệm của hệ phương trình tuyến tính:
[ 2.  3. -1.]


## Giải hệ phương trình tuyến tính sử dụng thư viện SymPy

In [29]:
import numpy as np
from scipy.linalg import solve

# Hệ số của ma trận A
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

# Hệ số của vế phải (tự do) b
b = np.array([8, -11, -3])

# Giải hệ phương trình tuyến tính Ax = b sử dụng SciPy
x = solve(A, b)

print("Nghiệm của hệ phương trình tuyến tính:")
print(x)


Nghiệm của hệ phương trình tuyến tính:
[ 2.  3. -1.]


## So sánh kết quả
Việc sử dụng các thư viện như NumPy, SciPy, và SymPy để giải hệ phương trình tuyến tính cho kết quả giống nhau. tuy nhiên Các thư viện thường được viết bằng ngôn ngữ lập trình được tối ưu hóa như C hoặc Fortran nên thường nhanh hơn so với các hàm viết bằng tay trong Python 